### ISSUE TITLE
Weird WA in UVA 11495 - Bubbles and Buckets

### ISSUE THREAD

**Issue by omarradwan** [AhmadElsagheer/Competitive-programming-library#28]
Carlos wins, if the inversion index is even. Otherwise, Marcelo wins.

The following line gets the code accepted:

`out.println(inversion % 2 == 0? "Carlos" : "Marcelo")`

However, this one gives WA!

`out.println(inversion % 2 == 1? "Marcelo" : "Carlos")`

[Problem Link](https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=2490)
[WA Code](https://www.ideone.com/Hk4VUW)
[AC Code](https://www.ideone.com/w59Nbz)

**Comment by david-perez** [comment]
There can be up to `(N * (N - 1)) / 2` inversions, where `N <= 100000`, so you have to use `long`.

**Comment by AhmadElsagheer** [comment]
There is a nice reason for the logic behind these verdicts

- x % y % 2 = x % 2 if y is a power of 2. Taking a number mod y (y = 2^k) is equivalent to removing any 1 in its binary representation at position >= k. So, if the number is even, it will remain even after taking it modulo any power of 2.
- The array length can reach 10^5 which means that inversion can overflow.
- Overflow is equivalent to taking a number modulo 2^32
- `-5 % 2 = -1`
- That's why it is ok to continue with `int` but you have to take care that modulo 2 must handle any form of an `int` (specifically negative integers)

The following formats are ok

- `inversion % 2 == 0` 
- `inversion % 2 != 0`
- `inversion % 2 == 1 || inversion % 2 == -1`
- `(inversion & 1) == 1`
- `(inversion & 1) != 0`
